#!/bin/bash
#sbatch -j fenicsx_7
#sbatch -n 1
#sbatch -t 48:00:00
#sbatch -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx-env
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 772
mpirun -n 32 python flow_past_cylinder.py --Re 773
mpirun -n 32 python flow_past_cylinder.py --Re 774
mpirun -n 32 python flow_past_cylinder.py --Re 775
mpirun -n 32 python flow_past_cylinder.py --Re 776
mpirun -n 32 python flow_past_cylinder.py --Re 777
mpirun -n 32 python flow_past_cylinder.py --Re 778
mpirun -n 32 python flow_past_cylinder.py --Re 779
mpirun -n 32 python flow_past_cylinder.py --Re 780
mpirun -n 32 python flow_past_cylinder.py --Re 781
mpirun -n 32 python flow_past_cylinder.py --Re 782
mpirun -n 32 python flow_past_cylinder.py --Re 783
mpirun -n 32 python flow_past_cylinder.py --Re 784
mpirun -n 32 python flow_past_cylinder.py --Re 785
mpirun -n 32 python flow_past_cylinder.py --Re 786
mpirun -n 32 python flow_past_cylinder.py --Re 787
mpirun -n 32 python flow_past_cylinder.py --Re 788
mpirun -n 32 python flow_past_cylinder.py --Re 789
mpirun -n 32 python flow_past_cylinder.py --Re 790
mpirun -n 32 python flow_past_cylinder.py --Re 791
mpirun -n 32 python flow_past_cylinder.py --Re 792
mpirun -n 32 python flow_past_cylinder.py --Re 793
mpirun -n 32 python flow_past_cylinder.py --Re 794
mpirun -n 32 python flow_past_cylinder.py --Re 795
mpirun -n 32 python flow_past_cylinder.py --Re 796
mpirun -n 32 python flow_past_cylinder.py --Re 797
mpirun -n 32 python flow_past_cylinder.py --Re 798
mpirun -n 32 python flow_past_cylinder.py --Re 799
mpirun -n 32 python flow_past_cylinder.py --Re 800
mpirun -n 32 python flow_past_cylinder.py --Re 801
mpirun -n 32 python flow_past_cylinder.py --Re 802
mpirun -n 32 python flow_past_cylinder.py --Re 803
mpirun -n 32 python flow_past_cylinder.py --Re 804
mpirun -n 32 python flow_past_cylinder.py --Re 805
mpirun -n 32 python flow_past_cylinder.py --Re 806
mpirun -n 32 python flow_past_cylinder.py --Re 807
mpirun -n 32 python flow_past_cylinder.py --Re 808
mpirun -n 32 python flow_past_cylinder.py --Re 809
mpirun -n 32 python flow_past_cylinder.py --Re 810
mpirun -n 32 python flow_past_cylinder.py --Re 811
mpirun -n 32 python flow_past_cylinder.py --Re 812
mpirun -n 32 python flow_past_cylinder.py --Re 813
mpirun -n 32 python flow_past_cylinder.py --Re 814
mpirun -n 32 python flow_past_cylinder.py --Re 815
mpirun -n 32 python flow_past_cylinder.py --Re 816
mpirun -n 32 python flow_past_cylinder.py --Re 817
mpirun -n 32 python flow_past_cylinder.py --Re 818
mpirun -n 32 python flow_past_cylinder.py --Re 819
mpirun -n 32 python flow_past_cylinder.py --Re 820
mpirun -n 32 python flow_past_cylinder.py --Re 821
mpirun -n 32 python flow_past_cylinder.py --Re 822
mpirun -n 32 python flow_past_cylinder.py --Re 823
mpirun -n 32 python flow_past_cylinder.py --Re 824
mpirun -n 32 python flow_past_cylinder.py --Re 825
mpirun -n 32 python flow_past_cylinder.py --Re 826
mpirun -n 32 python flow_past_cylinder.py --Re 827
mpirun -n 32 python flow_past_cylinder.py --Re 828
mpirun -n 32 python flow_past_cylinder.py --Re 829
mpirun -n 32 python flow_past_cylinder.py --Re 830
mpirun -n 32 python flow_past_cylinder.py --Re 831
mpirun -n 32 python flow_past_cylinder.py --Re 832
mpirun -n 32 python flow_past_cylinder.py --Re 833
mpirun -n 32 python flow_past_cylinder.py --Re 834
mpirun -n 32 python flow_past_cylinder.py --Re 835
mpirun -n 32 python flow_past_cylinder.py --Re 836
mpirun -n 32 python flow_past_cylinder.py --Re 837
mpirun -n 32 python flow_past_cylinder.py --Re 838
mpirun -n 32 python flow_past_cylinder.py --Re 839
mpirun -n 32 python flow_past_cylinder.py --Re 840
mpirun -n 32 python flow_past_cylinder.py --Re 841
mpirun -n 32 python flow_past_cylinder.py --Re 842
mpirun -n 32 python flow_past_cylinder.py --Re 843
mpirun -n 32 python flow_past_cylinder.py --Re 844
mpirun -n 32 python flow_past_cylinder.py --Re 845
mpirun -n 32 python flow_past_cylinder.py --Re 846
mpirun -n 32 python flow_past_cylinder.py --Re 847
mpirun -n 32 python flow_past_cylinder.py --Re 848
mpirun -n 32 python flow_past_cylinder.py --Re 849
mpirun -n 32 python flow_past_cylinder.py --Re 850
mpirun -n 32 python flow_past_cylinder.py --Re 851
mpirun -n 32 python flow_past_cylinder.py --Re 852
mpirun -n 32 python flow_past_cylinder.py --Re 853
mpirun -n 32 python flow_past_cylinder.py --Re 854
mpirun -n 32 python flow_past_cylinder.py --Re 855
mpirun -n 32 python flow_past_cylinder.py --Re 856
mpirun -n 32 python flow_past_cylinder.py --Re 857
mpirun -n 32 python flow_past_cylinder.py --Re 858
mpirun -n 32 python flow_past_cylinder.py --Re 859
mpirun -n 32 python flow_past_cylinder.py --Re 860
mpirun -n 32 python flow_past_cylinder.py --Re 861
mpirun -n 32 python flow_past_cylinder.py --Re 862
mpirun -n 32 python flow_past_cylinder.py --Re 863
mpirun -n 32 python flow_past_cylinder.py --Re 864
mpirun -n 32 python flow_past_cylinder.py --Re 865
mpirun -n 32 python flow_past_cylinder.py --Re 866
mpirun -n 32 python flow_past_cylinder.py --Re 867
