#!/bin/bash
#sbatch -j fenicsx_2
#sbatch -n 1
#sbatch -t 48:00:00
#sbatch -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx-env
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 292
mpirun -n 32 python flow_past_cylinder.py --Re 293
mpirun -n 32 python flow_past_cylinder.py --Re 294
mpirun -n 32 python flow_past_cylinder.py --Re 295
mpirun -n 32 python flow_past_cylinder.py --Re 296
mpirun -n 32 python flow_past_cylinder.py --Re 297
mpirun -n 32 python flow_past_cylinder.py --Re 298
mpirun -n 32 python flow_past_cylinder.py --Re 299
mpirun -n 32 python flow_past_cylinder.py --Re 300
mpirun -n 32 python flow_past_cylinder.py --Re 301
mpirun -n 32 python flow_past_cylinder.py --Re 302
mpirun -n 32 python flow_past_cylinder.py --Re 303
mpirun -n 32 python flow_past_cylinder.py --Re 304
mpirun -n 32 python flow_past_cylinder.py --Re 305
mpirun -n 32 python flow_past_cylinder.py --Re 306
mpirun -n 32 python flow_past_cylinder.py --Re 307
mpirun -n 32 python flow_past_cylinder.py --Re 308
mpirun -n 32 python flow_past_cylinder.py --Re 309
mpirun -n 32 python flow_past_cylinder.py --Re 310
mpirun -n 32 python flow_past_cylinder.py --Re 311
mpirun -n 32 python flow_past_cylinder.py --Re 312
mpirun -n 32 python flow_past_cylinder.py --Re 313
mpirun -n 32 python flow_past_cylinder.py --Re 314
mpirun -n 32 python flow_past_cylinder.py --Re 315
mpirun -n 32 python flow_past_cylinder.py --Re 316
mpirun -n 32 python flow_past_cylinder.py --Re 317
mpirun -n 32 python flow_past_cylinder.py --Re 318
mpirun -n 32 python flow_past_cylinder.py --Re 319
mpirun -n 32 python flow_past_cylinder.py --Re 320
mpirun -n 32 python flow_past_cylinder.py --Re 321
mpirun -n 32 python flow_past_cylinder.py --Re 322
mpirun -n 32 python flow_past_cylinder.py --Re 323
mpirun -n 32 python flow_past_cylinder.py --Re 324
mpirun -n 32 python flow_past_cylinder.py --Re 325
mpirun -n 32 python flow_past_cylinder.py --Re 326
mpirun -n 32 python flow_past_cylinder.py --Re 327
mpirun -n 32 python flow_past_cylinder.py --Re 328
mpirun -n 32 python flow_past_cylinder.py --Re 329
mpirun -n 32 python flow_past_cylinder.py --Re 330
mpirun -n 32 python flow_past_cylinder.py --Re 331
mpirun -n 32 python flow_past_cylinder.py --Re 332
mpirun -n 32 python flow_past_cylinder.py --Re 333
mpirun -n 32 python flow_past_cylinder.py --Re 334
mpirun -n 32 python flow_past_cylinder.py --Re 335
mpirun -n 32 python flow_past_cylinder.py --Re 336
mpirun -n 32 python flow_past_cylinder.py --Re 337
mpirun -n 32 python flow_past_cylinder.py --Re 338
mpirun -n 32 python flow_past_cylinder.py --Re 339
mpirun -n 32 python flow_past_cylinder.py --Re 340
mpirun -n 32 python flow_past_cylinder.py --Re 341
mpirun -n 32 python flow_past_cylinder.py --Re 342
mpirun -n 32 python flow_past_cylinder.py --Re 343
mpirun -n 32 python flow_past_cylinder.py --Re 344
mpirun -n 32 python flow_past_cylinder.py --Re 345
mpirun -n 32 python flow_past_cylinder.py --Re 346
mpirun -n 32 python flow_past_cylinder.py --Re 347
mpirun -n 32 python flow_past_cylinder.py --Re 348
mpirun -n 32 python flow_past_cylinder.py --Re 349
mpirun -n 32 python flow_past_cylinder.py --Re 350
mpirun -n 32 python flow_past_cylinder.py --Re 351
mpirun -n 32 python flow_past_cylinder.py --Re 352
mpirun -n 32 python flow_past_cylinder.py --Re 353
mpirun -n 32 python flow_past_cylinder.py --Re 354
mpirun -n 32 python flow_past_cylinder.py --Re 355
mpirun -n 32 python flow_past_cylinder.py --Re 356
mpirun -n 32 python flow_past_cylinder.py --Re 357
mpirun -n 32 python flow_past_cylinder.py --Re 358
mpirun -n 32 python flow_past_cylinder.py --Re 359
mpirun -n 32 python flow_past_cylinder.py --Re 360
mpirun -n 32 python flow_past_cylinder.py --Re 361
mpirun -n 32 python flow_past_cylinder.py --Re 362
mpirun -n 32 python flow_past_cylinder.py --Re 363
mpirun -n 32 python flow_past_cylinder.py --Re 364
mpirun -n 32 python flow_past_cylinder.py --Re 365
mpirun -n 32 python flow_past_cylinder.py --Re 366
mpirun -n 32 python flow_past_cylinder.py --Re 367
mpirun -n 32 python flow_past_cylinder.py --Re 368
mpirun -n 32 python flow_past_cylinder.py --Re 369
mpirun -n 32 python flow_past_cylinder.py --Re 370
mpirun -n 32 python flow_past_cylinder.py --Re 371
mpirun -n 32 python flow_past_cylinder.py --Re 372
mpirun -n 32 python flow_past_cylinder.py --Re 373
mpirun -n 32 python flow_past_cylinder.py --Re 374
mpirun -n 32 python flow_past_cylinder.py --Re 375
mpirun -n 32 python flow_past_cylinder.py --Re 376
mpirun -n 32 python flow_past_cylinder.py --Re 377
mpirun -n 32 python flow_past_cylinder.py --Re 378
mpirun -n 32 python flow_past_cylinder.py --Re 379
mpirun -n 32 python flow_past_cylinder.py --Re 380
mpirun -n 32 python flow_past_cylinder.py --Re 381
mpirun -n 32 python flow_past_cylinder.py --Re 382
mpirun -n 32 python flow_past_cylinder.py --Re 383
mpirun -n 32 python flow_past_cylinder.py --Re 384
mpirun -n 32 python flow_past_cylinder.py --Re 385
mpirun -n 32 python flow_past_cylinder.py --Re 386
mpirun -n 32 python flow_past_cylinder.py --Re 387
