#!/bin/bash
#sbatch -j fenicsx_6
#sbatch -n 1
#sbatch -t 48:00:00
#sbatch -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 676
mpirun -n 32 python flow_past_cylinder.py --Re 677
mpirun -n 32 python flow_past_cylinder.py --Re 678
mpirun -n 32 python flow_past_cylinder.py --Re 679
mpirun -n 32 python flow_past_cylinder.py --Re 680
mpirun -n 32 python flow_past_cylinder.py --Re 681
mpirun -n 32 python flow_past_cylinder.py --Re 682
mpirun -n 32 python flow_past_cylinder.py --Re 683
mpirun -n 32 python flow_past_cylinder.py --Re 684
mpirun -n 32 python flow_past_cylinder.py --Re 685
mpirun -n 32 python flow_past_cylinder.py --Re 686
mpirun -n 32 python flow_past_cylinder.py --Re 687
mpirun -n 32 python flow_past_cylinder.py --Re 688
mpirun -n 32 python flow_past_cylinder.py --Re 689
mpirun -n 32 python flow_past_cylinder.py --Re 690
mpirun -n 32 python flow_past_cylinder.py --Re 691
mpirun -n 32 python flow_past_cylinder.py --Re 692
mpirun -n 32 python flow_past_cylinder.py --Re 693
mpirun -n 32 python flow_past_cylinder.py --Re 694
mpirun -n 32 python flow_past_cylinder.py --Re 695
mpirun -n 32 python flow_past_cylinder.py --Re 696
mpirun -n 32 python flow_past_cylinder.py --Re 697
mpirun -n 32 python flow_past_cylinder.py --Re 698
mpirun -n 32 python flow_past_cylinder.py --Re 699
mpirun -n 32 python flow_past_cylinder.py --Re 700
mpirun -n 32 python flow_past_cylinder.py --Re 701
mpirun -n 32 python flow_past_cylinder.py --Re 702
mpirun -n 32 python flow_past_cylinder.py --Re 703
mpirun -n 32 python flow_past_cylinder.py --Re 704
mpirun -n 32 python flow_past_cylinder.py --Re 705
mpirun -n 32 python flow_past_cylinder.py --Re 706
mpirun -n 32 python flow_past_cylinder.py --Re 707
mpirun -n 32 python flow_past_cylinder.py --Re 708
mpirun -n 32 python flow_past_cylinder.py --Re 709
mpirun -n 32 python flow_past_cylinder.py --Re 710
mpirun -n 32 python flow_past_cylinder.py --Re 711
mpirun -n 32 python flow_past_cylinder.py --Re 712
mpirun -n 32 python flow_past_cylinder.py --Re 713
mpirun -n 32 python flow_past_cylinder.py --Re 714
mpirun -n 32 python flow_past_cylinder.py --Re 715
mpirun -n 32 python flow_past_cylinder.py --Re 716
mpirun -n 32 python flow_past_cylinder.py --Re 717
mpirun -n 32 python flow_past_cylinder.py --Re 718
mpirun -n 32 python flow_past_cylinder.py --Re 719
mpirun -n 32 python flow_past_cylinder.py --Re 720
mpirun -n 32 python flow_past_cylinder.py --Re 721
mpirun -n 32 python flow_past_cylinder.py --Re 722
mpirun -n 32 python flow_past_cylinder.py --Re 723
mpirun -n 32 python flow_past_cylinder.py --Re 724
mpirun -n 32 python flow_past_cylinder.py --Re 725
mpirun -n 32 python flow_past_cylinder.py --Re 726
mpirun -n 32 python flow_past_cylinder.py --Re 727
mpirun -n 32 python flow_past_cylinder.py --Re 728
mpirun -n 32 python flow_past_cylinder.py --Re 729
mpirun -n 32 python flow_past_cylinder.py --Re 730
mpirun -n 32 python flow_past_cylinder.py --Re 731
mpirun -n 32 python flow_past_cylinder.py --Re 732
mpirun -n 32 python flow_past_cylinder.py --Re 733
mpirun -n 32 python flow_past_cylinder.py --Re 734
mpirun -n 32 python flow_past_cylinder.py --Re 735
mpirun -n 32 python flow_past_cylinder.py --Re 736
mpirun -n 32 python flow_past_cylinder.py --Re 737
mpirun -n 32 python flow_past_cylinder.py --Re 738
mpirun -n 32 python flow_past_cylinder.py --Re 739
mpirun -n 32 python flow_past_cylinder.py --Re 740
mpirun -n 32 python flow_past_cylinder.py --Re 741
mpirun -n 32 python flow_past_cylinder.py --Re 742
mpirun -n 32 python flow_past_cylinder.py --Re 743
mpirun -n 32 python flow_past_cylinder.py --Re 744
mpirun -n 32 python flow_past_cylinder.py --Re 745
mpirun -n 32 python flow_past_cylinder.py --Re 746
mpirun -n 32 python flow_past_cylinder.py --Re 747
mpirun -n 32 python flow_past_cylinder.py --Re 748
mpirun -n 32 python flow_past_cylinder.py --Re 749
mpirun -n 32 python flow_past_cylinder.py --Re 750
mpirun -n 32 python flow_past_cylinder.py --Re 751
mpirun -n 32 python flow_past_cylinder.py --Re 752
mpirun -n 32 python flow_past_cylinder.py --Re 753
mpirun -n 32 python flow_past_cylinder.py --Re 754
mpirun -n 32 python flow_past_cylinder.py --Re 755
mpirun -n 32 python flow_past_cylinder.py --Re 756
mpirun -n 32 python flow_past_cylinder.py --Re 757
mpirun -n 32 python flow_past_cylinder.py --Re 758
mpirun -n 32 python flow_past_cylinder.py --Re 759
mpirun -n 32 python flow_past_cylinder.py --Re 760
mpirun -n 32 python flow_past_cylinder.py --Re 761
mpirun -n 32 python flow_past_cylinder.py --Re 762
mpirun -n 32 python flow_past_cylinder.py --Re 763
mpirun -n 32 python flow_past_cylinder.py --Re 764
mpirun -n 32 python flow_past_cylinder.py --Re 765
mpirun -n 32 python flow_past_cylinder.py --Re 766
mpirun -n 32 python flow_past_cylinder.py --Re 767
mpirun -n 32 python flow_past_cylinder.py --Re 768
mpirun -n 32 python flow_past_cylinder.py --Re 769
mpirun -n 32 python flow_past_cylinder.py --Re 770
mpirun -n 32 python flow_past_cylinder.py --Re 771
