#!/bin/bash
#sbatch -j fenicsx_5
#sbatch -n 1
#sbatch -t 48:00:00
#sbatch -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx-env
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 580
mpirun -n 32 python flow_past_cylinder.py --Re 581
mpirun -n 32 python flow_past_cylinder.py --Re 582
mpirun -n 32 python flow_past_cylinder.py --Re 583
mpirun -n 32 python flow_past_cylinder.py --Re 584
mpirun -n 32 python flow_past_cylinder.py --Re 585
mpirun -n 32 python flow_past_cylinder.py --Re 586
mpirun -n 32 python flow_past_cylinder.py --Re 587
mpirun -n 32 python flow_past_cylinder.py --Re 588
mpirun -n 32 python flow_past_cylinder.py --Re 589
mpirun -n 32 python flow_past_cylinder.py --Re 590
mpirun -n 32 python flow_past_cylinder.py --Re 591
mpirun -n 32 python flow_past_cylinder.py --Re 592
mpirun -n 32 python flow_past_cylinder.py --Re 593
mpirun -n 32 python flow_past_cylinder.py --Re 594
mpirun -n 32 python flow_past_cylinder.py --Re 595
mpirun -n 32 python flow_past_cylinder.py --Re 596
mpirun -n 32 python flow_past_cylinder.py --Re 597
mpirun -n 32 python flow_past_cylinder.py --Re 598
mpirun -n 32 python flow_past_cylinder.py --Re 599
mpirun -n 32 python flow_past_cylinder.py --Re 600
mpirun -n 32 python flow_past_cylinder.py --Re 601
mpirun -n 32 python flow_past_cylinder.py --Re 602
mpirun -n 32 python flow_past_cylinder.py --Re 603
mpirun -n 32 python flow_past_cylinder.py --Re 604
mpirun -n 32 python flow_past_cylinder.py --Re 605
mpirun -n 32 python flow_past_cylinder.py --Re 606
mpirun -n 32 python flow_past_cylinder.py --Re 607
mpirun -n 32 python flow_past_cylinder.py --Re 608
mpirun -n 32 python flow_past_cylinder.py --Re 609
mpirun -n 32 python flow_past_cylinder.py --Re 610
mpirun -n 32 python flow_past_cylinder.py --Re 611
mpirun -n 32 python flow_past_cylinder.py --Re 612
mpirun -n 32 python flow_past_cylinder.py --Re 613
mpirun -n 32 python flow_past_cylinder.py --Re 614
mpirun -n 32 python flow_past_cylinder.py --Re 615
mpirun -n 32 python flow_past_cylinder.py --Re 616
mpirun -n 32 python flow_past_cylinder.py --Re 617
mpirun -n 32 python flow_past_cylinder.py --Re 618
mpirun -n 32 python flow_past_cylinder.py --Re 619
mpirun -n 32 python flow_past_cylinder.py --Re 620
mpirun -n 32 python flow_past_cylinder.py --Re 621
mpirun -n 32 python flow_past_cylinder.py --Re 622
mpirun -n 32 python flow_past_cylinder.py --Re 623
mpirun -n 32 python flow_past_cylinder.py --Re 624
mpirun -n 32 python flow_past_cylinder.py --Re 625
mpirun -n 32 python flow_past_cylinder.py --Re 626
mpirun -n 32 python flow_past_cylinder.py --Re 627
mpirun -n 32 python flow_past_cylinder.py --Re 628
mpirun -n 32 python flow_past_cylinder.py --Re 629
mpirun -n 32 python flow_past_cylinder.py --Re 630
mpirun -n 32 python flow_past_cylinder.py --Re 631
mpirun -n 32 python flow_past_cylinder.py --Re 632
mpirun -n 32 python flow_past_cylinder.py --Re 633
mpirun -n 32 python flow_past_cylinder.py --Re 634
mpirun -n 32 python flow_past_cylinder.py --Re 635
mpirun -n 32 python flow_past_cylinder.py --Re 636
mpirun -n 32 python flow_past_cylinder.py --Re 637
mpirun -n 32 python flow_past_cylinder.py --Re 638
mpirun -n 32 python flow_past_cylinder.py --Re 639
mpirun -n 32 python flow_past_cylinder.py --Re 640
mpirun -n 32 python flow_past_cylinder.py --Re 641
mpirun -n 32 python flow_past_cylinder.py --Re 642
mpirun -n 32 python flow_past_cylinder.py --Re 643
mpirun -n 32 python flow_past_cylinder.py --Re 644
mpirun -n 32 python flow_past_cylinder.py --Re 645
mpirun -n 32 python flow_past_cylinder.py --Re 646
mpirun -n 32 python flow_past_cylinder.py --Re 647
mpirun -n 32 python flow_past_cylinder.py --Re 648
mpirun -n 32 python flow_past_cylinder.py --Re 649
mpirun -n 32 python flow_past_cylinder.py --Re 650
mpirun -n 32 python flow_past_cylinder.py --Re 651
mpirun -n 32 python flow_past_cylinder.py --Re 652
mpirun -n 32 python flow_past_cylinder.py --Re 653
mpirun -n 32 python flow_past_cylinder.py --Re 654
mpirun -n 32 python flow_past_cylinder.py --Re 655
mpirun -n 32 python flow_past_cylinder.py --Re 656
mpirun -n 32 python flow_past_cylinder.py --Re 657
mpirun -n 32 python flow_past_cylinder.py --Re 658
mpirun -n 32 python flow_past_cylinder.py --Re 659
mpirun -n 32 python flow_past_cylinder.py --Re 660
mpirun -n 32 python flow_past_cylinder.py --Re 661
mpirun -n 32 python flow_past_cylinder.py --Re 662
mpirun -n 32 python flow_past_cylinder.py --Re 663
mpirun -n 32 python flow_past_cylinder.py --Re 664
mpirun -n 32 python flow_past_cylinder.py --Re 665
mpirun -n 32 python flow_past_cylinder.py --Re 666
mpirun -n 32 python flow_past_cylinder.py --Re 667
mpirun -n 32 python flow_past_cylinder.py --Re 668
mpirun -n 32 python flow_past_cylinder.py --Re 669
mpirun -n 32 python flow_past_cylinder.py --Re 670
mpirun -n 32 python flow_past_cylinder.py --Re 671
mpirun -n 32 python flow_past_cylinder.py --Re 672
mpirun -n 32 python flow_past_cylinder.py --Re 673
mpirun -n 32 python flow_past_cylinder.py --Re 674
mpirun -n 32 python flow_past_cylinder.py --Re 675
