#!/bin/bash
#SBATCH -j fenicsx_3
#SBATCH -n 1
#SBATCH -t 48:00:00
#SBATCH -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx-env
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 388
mpirun -n 32 python flow_past_cylinder.py --Re 389
mpirun -n 32 python flow_past_cylinder.py --Re 390
mpirun -n 32 python flow_past_cylinder.py --Re 391
mpirun -n 32 python flow_past_cylinder.py --Re 392
mpirun -n 32 python flow_past_cylinder.py --Re 393
mpirun -n 32 python flow_past_cylinder.py --Re 394
mpirun -n 32 python flow_past_cylinder.py --Re 395
mpirun -n 32 python flow_past_cylinder.py --Re 396
mpirun -n 32 python flow_past_cylinder.py --Re 397
mpirun -n 32 python flow_past_cylinder.py --Re 398
mpirun -n 32 python flow_past_cylinder.py --Re 399
mpirun -n 32 python flow_past_cylinder.py --Re 400
mpirun -n 32 python flow_past_cylinder.py --Re 401
mpirun -n 32 python flow_past_cylinder.py --Re 402
mpirun -n 32 python flow_past_cylinder.py --Re 403
mpirun -n 32 python flow_past_cylinder.py --Re 404
mpirun -n 32 python flow_past_cylinder.py --Re 405
mpirun -n 32 python flow_past_cylinder.py --Re 406
mpirun -n 32 python flow_past_cylinder.py --Re 407
mpirun -n 32 python flow_past_cylinder.py --Re 408
mpirun -n 32 python flow_past_cylinder.py --Re 409
mpirun -n 32 python flow_past_cylinder.py --Re 410
mpirun -n 32 python flow_past_cylinder.py --Re 411
mpirun -n 32 python flow_past_cylinder.py --Re 412
mpirun -n 32 python flow_past_cylinder.py --Re 413
mpirun -n 32 python flow_past_cylinder.py --Re 414
mpirun -n 32 python flow_past_cylinder.py --Re 415
mpirun -n 32 python flow_past_cylinder.py --Re 416
mpirun -n 32 python flow_past_cylinder.py --Re 417
mpirun -n 32 python flow_past_cylinder.py --Re 418
mpirun -n 32 python flow_past_cylinder.py --Re 419
mpirun -n 32 python flow_past_cylinder.py --Re 420
mpirun -n 32 python flow_past_cylinder.py --Re 421
mpirun -n 32 python flow_past_cylinder.py --Re 422
mpirun -n 32 python flow_past_cylinder.py --Re 423
mpirun -n 32 python flow_past_cylinder.py --Re 424
mpirun -n 32 python flow_past_cylinder.py --Re 425
mpirun -n 32 python flow_past_cylinder.py --Re 426
mpirun -n 32 python flow_past_cylinder.py --Re 427
mpirun -n 32 python flow_past_cylinder.py --Re 428
mpirun -n 32 python flow_past_cylinder.py --Re 429
mpirun -n 32 python flow_past_cylinder.py --Re 430
mpirun -n 32 python flow_past_cylinder.py --Re 431
mpirun -n 32 python flow_past_cylinder.py --Re 432
mpirun -n 32 python flow_past_cylinder.py --Re 433
mpirun -n 32 python flow_past_cylinder.py --Re 434
mpirun -n 32 python flow_past_cylinder.py --Re 435
mpirun -n 32 python flow_past_cylinder.py --Re 436
mpirun -n 32 python flow_past_cylinder.py --Re 437
mpirun -n 32 python flow_past_cylinder.py --Re 438
mpirun -n 32 python flow_past_cylinder.py --Re 439
mpirun -n 32 python flow_past_cylinder.py --Re 440
mpirun -n 32 python flow_past_cylinder.py --Re 441
mpirun -n 32 python flow_past_cylinder.py --Re 442
mpirun -n 32 python flow_past_cylinder.py --Re 443
mpirun -n 32 python flow_past_cylinder.py --Re 444
mpirun -n 32 python flow_past_cylinder.py --Re 445
mpirun -n 32 python flow_past_cylinder.py --Re 446
mpirun -n 32 python flow_past_cylinder.py --Re 447
mpirun -n 32 python flow_past_cylinder.py --Re 448
mpirun -n 32 python flow_past_cylinder.py --Re 449
mpirun -n 32 python flow_past_cylinder.py --Re 450
mpirun -n 32 python flow_past_cylinder.py --Re 451
mpirun -n 32 python flow_past_cylinder.py --Re 452
mpirun -n 32 python flow_past_cylinder.py --Re 453
mpirun -n 32 python flow_past_cylinder.py --Re 454
mpirun -n 32 python flow_past_cylinder.py --Re 455
mpirun -n 32 python flow_past_cylinder.py --Re 456
mpirun -n 32 python flow_past_cylinder.py --Re 457
mpirun -n 32 python flow_past_cylinder.py --Re 458
mpirun -n 32 python flow_past_cylinder.py --Re 459
mpirun -n 32 python flow_past_cylinder.py --Re 460
mpirun -n 32 python flow_past_cylinder.py --Re 461
mpirun -n 32 python flow_past_cylinder.py --Re 462
mpirun -n 32 python flow_past_cylinder.py --Re 463
mpirun -n 32 python flow_past_cylinder.py --Re 464
mpirun -n 32 python flow_past_cylinder.py --Re 465
mpirun -n 32 python flow_past_cylinder.py --Re 466
mpirun -n 32 python flow_past_cylinder.py --Re 467
mpirun -n 32 python flow_past_cylinder.py --Re 468
mpirun -n 32 python flow_past_cylinder.py --Re 469
mpirun -n 32 python flow_past_cylinder.py --Re 470
mpirun -n 32 python flow_past_cylinder.py --Re 471
mpirun -n 32 python flow_past_cylinder.py --Re 472
mpirun -n 32 python flow_past_cylinder.py --Re 473
mpirun -n 32 python flow_past_cylinder.py --Re 474
mpirun -n 32 python flow_past_cylinder.py --Re 475
mpirun -n 32 python flow_past_cylinder.py --Re 476
mpirun -n 32 python flow_past_cylinder.py --Re 477
mpirun -n 32 python flow_past_cylinder.py --Re 478
mpirun -n 32 python flow_past_cylinder.py --Re 479
mpirun -n 32 python flow_past_cylinder.py --Re 480
mpirun -n 32 python flow_past_cylinder.py --Re 481
mpirun -n 32 python flow_past_cylinder.py --Re 482
mpirun -n 32 python flow_past_cylinder.py --Re 483
