#!/bin/bash
#sbatch -j fenicsx_4
#sbatch -n 1
#sbatch -t 48:00:00
#sbatch -p cpu
eval "$(/opt/ohpc/pub/compiler/anaconda3/2024.02-1/bin/conda shell.bash hook)"
conda activate fenicsx-env
cd /home/darve/mcc4/psaap-data-science/multimodal-toy-problems/fenics
mpirun -n 32 python flow_past_cylinder.py --Re 484
mpirun -n 32 python flow_past_cylinder.py --Re 485
mpirun -n 32 python flow_past_cylinder.py --Re 486
mpirun -n 32 python flow_past_cylinder.py --Re 487
mpirun -n 32 python flow_past_cylinder.py --Re 488
mpirun -n 32 python flow_past_cylinder.py --Re 489
mpirun -n 32 python flow_past_cylinder.py --Re 490
mpirun -n 32 python flow_past_cylinder.py --Re 491
mpirun -n 32 python flow_past_cylinder.py --Re 492
mpirun -n 32 python flow_past_cylinder.py --Re 493
mpirun -n 32 python flow_past_cylinder.py --Re 494
mpirun -n 32 python flow_past_cylinder.py --Re 495
mpirun -n 32 python flow_past_cylinder.py --Re 496
mpirun -n 32 python flow_past_cylinder.py --Re 497
mpirun -n 32 python flow_past_cylinder.py --Re 498
mpirun -n 32 python flow_past_cylinder.py --Re 499
mpirun -n 32 python flow_past_cylinder.py --Re 500
mpirun -n 32 python flow_past_cylinder.py --Re 501
mpirun -n 32 python flow_past_cylinder.py --Re 502
mpirun -n 32 python flow_past_cylinder.py --Re 503
mpirun -n 32 python flow_past_cylinder.py --Re 504
mpirun -n 32 python flow_past_cylinder.py --Re 505
mpirun -n 32 python flow_past_cylinder.py --Re 506
mpirun -n 32 python flow_past_cylinder.py --Re 507
mpirun -n 32 python flow_past_cylinder.py --Re 508
mpirun -n 32 python flow_past_cylinder.py --Re 509
mpirun -n 32 python flow_past_cylinder.py --Re 510
mpirun -n 32 python flow_past_cylinder.py --Re 511
mpirun -n 32 python flow_past_cylinder.py --Re 512
mpirun -n 32 python flow_past_cylinder.py --Re 513
mpirun -n 32 python flow_past_cylinder.py --Re 514
mpirun -n 32 python flow_past_cylinder.py --Re 515
mpirun -n 32 python flow_past_cylinder.py --Re 516
mpirun -n 32 python flow_past_cylinder.py --Re 517
mpirun -n 32 python flow_past_cylinder.py --Re 518
mpirun -n 32 python flow_past_cylinder.py --Re 519
mpirun -n 32 python flow_past_cylinder.py --Re 520
mpirun -n 32 python flow_past_cylinder.py --Re 521
mpirun -n 32 python flow_past_cylinder.py --Re 522
mpirun -n 32 python flow_past_cylinder.py --Re 523
mpirun -n 32 python flow_past_cylinder.py --Re 524
mpirun -n 32 python flow_past_cylinder.py --Re 525
mpirun -n 32 python flow_past_cylinder.py --Re 526
mpirun -n 32 python flow_past_cylinder.py --Re 527
mpirun -n 32 python flow_past_cylinder.py --Re 528
mpirun -n 32 python flow_past_cylinder.py --Re 529
mpirun -n 32 python flow_past_cylinder.py --Re 530
mpirun -n 32 python flow_past_cylinder.py --Re 531
mpirun -n 32 python flow_past_cylinder.py --Re 532
mpirun -n 32 python flow_past_cylinder.py --Re 533
mpirun -n 32 python flow_past_cylinder.py --Re 534
mpirun -n 32 python flow_past_cylinder.py --Re 535
mpirun -n 32 python flow_past_cylinder.py --Re 536
mpirun -n 32 python flow_past_cylinder.py --Re 537
mpirun -n 32 python flow_past_cylinder.py --Re 538
mpirun -n 32 python flow_past_cylinder.py --Re 539
mpirun -n 32 python flow_past_cylinder.py --Re 540
mpirun -n 32 python flow_past_cylinder.py --Re 541
mpirun -n 32 python flow_past_cylinder.py --Re 542
mpirun -n 32 python flow_past_cylinder.py --Re 543
mpirun -n 32 python flow_past_cylinder.py --Re 544
mpirun -n 32 python flow_past_cylinder.py --Re 545
mpirun -n 32 python flow_past_cylinder.py --Re 546
mpirun -n 32 python flow_past_cylinder.py --Re 547
mpirun -n 32 python flow_past_cylinder.py --Re 548
mpirun -n 32 python flow_past_cylinder.py --Re 549
mpirun -n 32 python flow_past_cylinder.py --Re 550
mpirun -n 32 python flow_past_cylinder.py --Re 551
mpirun -n 32 python flow_past_cylinder.py --Re 552
mpirun -n 32 python flow_past_cylinder.py --Re 553
mpirun -n 32 python flow_past_cylinder.py --Re 554
mpirun -n 32 python flow_past_cylinder.py --Re 555
mpirun -n 32 python flow_past_cylinder.py --Re 556
mpirun -n 32 python flow_past_cylinder.py --Re 557
mpirun -n 32 python flow_past_cylinder.py --Re 558
mpirun -n 32 python flow_past_cylinder.py --Re 559
mpirun -n 32 python flow_past_cylinder.py --Re 560
mpirun -n 32 python flow_past_cylinder.py --Re 561
mpirun -n 32 python flow_past_cylinder.py --Re 562
mpirun -n 32 python flow_past_cylinder.py --Re 563
mpirun -n 32 python flow_past_cylinder.py --Re 564
mpirun -n 32 python flow_past_cylinder.py --Re 565
mpirun -n 32 python flow_past_cylinder.py --Re 566
mpirun -n 32 python flow_past_cylinder.py --Re 567
mpirun -n 32 python flow_past_cylinder.py --Re 568
mpirun -n 32 python flow_past_cylinder.py --Re 569
mpirun -n 32 python flow_past_cylinder.py --Re 570
mpirun -n 32 python flow_past_cylinder.py --Re 571
mpirun -n 32 python flow_past_cylinder.py --Re 572
mpirun -n 32 python flow_past_cylinder.py --Re 573
mpirun -n 32 python flow_past_cylinder.py --Re 574
mpirun -n 32 python flow_past_cylinder.py --Re 575
mpirun -n 32 python flow_past_cylinder.py --Re 576
mpirun -n 32 python flow_past_cylinder.py --Re 577
mpirun -n 32 python flow_past_cylinder.py --Re 578
mpirun -n 32 python flow_past_cylinder.py --Re 579
